#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : matplotlib-inline
Version  : 0.1.2
Release  : 1
URL      : https://files.pythonhosted.org/packages/c1/fb/3361c4bf5ae8ffb9249132e70f4853ef511c0894a938fdff29320df55534/matplotlib-inline-0.1.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/c1/fb/3361c4bf5ae8ffb9249132e70f4853ef511c0894a938fdff29320df55534/matplotlib-inline-0.1.2.tar.gz
Summary  : Inline Matplotlib backend for Jupyter
Group    : Development/Tools
License  : BSD-3-Clause
Requires: matplotlib-inline-python = %{version}-%{release}
Requires: matplotlib-inline-python3 = %{version}-%{release}
Requires: traitlets
BuildRequires : buildreq-distutils3
BuildRequires : traitlets

%description
# Matplotlib Inline Back-end for IPython and Jupyter
## Installation
With conda:

%package python
Summary: python components for the matplotlib-inline package.
Group: Default
Requires: matplotlib-inline-python3 = %{version}-%{release}

%description python
python components for the matplotlib-inline package.


%package python3
Summary: python3 components for the matplotlib-inline package.
Group: Default
Requires: python3-core
Provides: pypi(matplotlib_inline)
Requires: pypi(traitlets)

%description python3
python3 components for the matplotlib-inline package.


%prep
%setup -q -n matplotlib-inline-0.1.2
cd %{_builddir}/matplotlib-inline-0.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620229997
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
